In [1]:
!pip install numpy

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [2]:
import numpy as np

C:\Users\skme2\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [4]:
lst1 = list(range(1,11))

In [5]:
lst1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
lst1**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
%timeit [i**2 for i in lst1]

7.86 µs ± 293 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
arr = np.array(lst1)

In [13]:
%timeit (arr**2)

1.74 µs ± 47.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
lst1 +[ 2]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2]

In [17]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
g = [1,4,8,9,10,12,13]

In [20]:
g

[1, 4, 8, 9, 10, 12, 13]

In [22]:
arr2 =   np.array(g)

In [23]:
arr2

array([ 1,  4,  8,  9, 10, 12, 13])

In [24]:
type(arr2)

numpy.ndarray

In [25]:
arr2.ndim

1

In [26]:
arr2.shape

(7,)

In [28]:
arr3 = np.arange(1,21)

In [29]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
arr4 = np.arange(2,31,3)

In [32]:
arr4

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [33]:
lst_2d = [[1,2,3], [4,5,6], [7,8,9]]

In [34]:
lst_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [36]:
arr_2d = np.array(lst_2d)

In [37]:
arr_2d.ndim

2

In [38]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr_2d.shape

(3, 3)

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.diag([9])

array([[9]])

In [45]:
np.diag([4,5,9,2])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 2]])

In [46]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [50]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
#Indexing in Array

In [56]:
np.random.randint(10,100)

85

In [58]:
new_arr = np.random.randint(10,100, (5,4))

In [59]:
new_arr

array([[41, 52, 99, 78],
       [77, 58, 56, 55],
       [57, 67, 86, 72],
       [57, 60, 87, 98],
       [97, 73, 58, 75]])

In [60]:
new_arr.shape

(5, 4)

In [62]:
new_arr[0]

array([41, 52, 99, 78])

In [63]:
new_arr[1]

array([77, 58, 56, 55])

In [64]:
new_arr[3]

array([57, 60, 87, 98])

In [65]:
new_arr

array([[41, 52, 99, 78],
       [77, 58, 56, 55],
       [57, 67, 86, 72],
       [57, 60, 87, 98],
       [97, 73, 58, 75]])

In [66]:
new_arr[-1]

array([97, 73, 58, 75])

In [67]:
new_arr[-3]

array([57, 67, 86, 72])

In [69]:
new_arr[:,0]

array([41, 77, 57, 57, 97])

In [71]:
new_arr[:,-1]

array([78, 55, 72, 98, 75])

In [72]:
new_arr

array([[41, 52, 99, 78],
       [77, 58, 56, 55],
       [57, 67, 86, 72],
       [57, 60, 87, 98],
       [97, 73, 58, 75]])

In [75]:
new_arr[0,0]

41

In [78]:
new_arr[1:3, 1:3]

array([[58, 56],
       [67, 86]])

In [84]:
new_arr[-4:-2, -3:-1]

array([[58, 56],
       [67, 86]])

In [87]:
new_arr[2:,1:]

array([[67, 86, 72],
       [60, 87, 98],
       [73, 58, 75]])

In [89]:
new_arr[:,-2]

array([99, 56, 86, 87, 58])

In [93]:
new_arr[1,1] = 460

In [94]:
new_arr

array([[ 41,  52,  99,  78],
       [ 77, 460,  56,  55],
       [ 57,  67,  86,  72],
       [ 57,  60,  87,  98],
       [ 97,  73,  58,  75]])

In [98]:
new_arr[-2:, -2:] = 150

In [99]:
new_arr

array([[ 41,  52,  99,  78],
       [ 77, 460,  56,  55],
       [ 57,  67,  86,  72],
       [ 57,  60, 150, 150],
       [ 97,  73, 150, 150]])

In [100]:
# msking

In [102]:
new_arr>10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [104]:
new_arr>50

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [107]:
np.sum(new_arr>100)

5

In [110]:
np.sum(new_arr[new_arr>100])

1060

In [111]:
#Basic Operations in Arrays

In [113]:
a = np.array([10,20,30,40])

In [115]:
b = np.arange(1,5)

In [116]:
a

array([10, 20, 30, 40])

In [117]:
b

array([1, 2, 3, 4])

In [118]:
a + b

array([11, 22, 33, 44])

In [119]:
a-b

array([ 9, 18, 27, 36])

In [120]:
a*b

array([ 10,  40,  90, 160])

In [121]:
a/b

array([10., 10., 10., 10.])

In [122]:
a**2

array([ 100,  400,  900, 1600])

In [123]:
b**3

array([ 1,  8, 27, 64], dtype=int32)

In [127]:
np.sum(a[a>20])

70

In [128]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [129]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [130]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [133]:
a = np.random.randint(0,5, (3,4))

In [136]:
b = np.random.randint(5,60,(4,3))

In [137]:
a * b 

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [138]:
np.dot(a,b)

array([[287, 231, 299],
       [324, 330, 310],
       [114, 118, 158]])

In [139]:
#More Operations on Arrays

In [141]:
d = np.arange(0,24)

In [142]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [143]:
d.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [144]:
d.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [145]:
d.reshape(10,8)

ValueError: cannot reshape array of size 24 into shape (10,8)

In [148]:
d = d.reshape(6,4)

In [149]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [150]:
np.sqrt(d)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [151]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [152]:
np.sum(d)

276

In [153]:
np.sum(d, axis=0)

array([60, 66, 72, 78])

In [154]:
np.sum(d, axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [155]:
np.max(d)

23

In [156]:
np.max(d, axis=0)

array([20, 21, 22, 23])

In [157]:
np.min(d, axis=1)

array([ 0,  4,  8, 12, 16, 20])

In [158]:
np.mean(d)

11.5

In [159]:
np.mean(d, axis=0)

array([10., 11., 12., 13.])

In [160]:
np.std(d)

6.922186552431729

In [161]:
np.std(d, axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399])

In [162]:
np.median(d)

11.5

In [163]:
np.median(d, axis=0)

array([10., 11., 12., 13.])

In [164]:
np.median(d, axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [165]:
#Shape Manipulation

In [166]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [169]:
d = d.flatten()

In [170]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [172]:
d = d.reshape(3,8)

In [173]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [174]:
d.T

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [175]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [176]:
np.transpose(d)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [177]:
# Stacking of arrays - vstack - hstack

In [179]:
p = np.random.randint(0,10,(2,2))

In [181]:
q = np.random.randint(0,10,(2,2))

In [182]:
p

array([[0, 9],
       [4, 8]])

In [183]:
q

array([[6, 1],
       [0, 1]])

In [184]:
np.vstack((p,q))

array([[0, 9],
       [4, 8],
       [6, 1],
       [0, 1]])

In [185]:
np.hstack((p,q))

array([[0, 9, 6, 1],
       [4, 8, 0, 1]])

In [186]:
#Broadcasting

In [190]:
x = np.random.randint(0,10,size =  (3,3))

In [191]:
x


array([[5, 3, 7],
       [1, 0, 3],
       [2, 6, 7]])

In [208]:
y = np.array([[1,2,3]])

In [209]:
y

array([[1, 2, 3]])

In [210]:
x.shape

(3, 3)

In [211]:
y.shape

(1, 3)

In [212]:
x

array([[5, 3, 7],
       [1, 0, 3],
       [2, 6, 7]])

In [213]:
y

array([[1, 2, 3]])

In [214]:
x +y

array([[ 6,  5, 10],
       [ 2,  2,  6],
       [ 3,  8, 10]])

In [215]:
x-y

array([[ 4,  1,  4],
       [ 0, -2,  0],
       [ 1,  4,  4]])

In [216]:
x*y

array([[ 5,  6, 21],
       [ 1,  0,  9],
       [ 2, 12, 21]])

In [217]:
x

array([[5, 3, 7],
       [1, 0, 3],
       [2, 6, 7]])

In [218]:
x.T + y

array([[ 6,  3,  5],
       [ 4,  2,  9],
       [ 8,  5, 10]])

In [219]:
y.T

array([[1],
       [2],
       [3]])

In [220]:
x

array([[5, 3, 7],
       [1, 0, 3],
       [2, 6, 7]])

In [221]:
x + 6

array([[11,  9, 13],
       [ 7,  6,  9],
       [ 8, 12, 13]])

In [222]:
p = [1,2,4,7,-2,9,6,0]

In [223]:
q = [5,5,8,2,-9,2,1,6]

In [224]:
ttl = 0
for i in range(len(p)):
    ttl+=(q[i] - p[i])**2

In [225]:
ttl**0.5

15.0

In [226]:
p1 = np.array(p)

In [227]:
p2 = np.array(q)

In [228]:
p1

array([ 1,  2,  4,  7, -2,  9,  6,  0])

In [229]:
p2

array([ 5,  5,  8,  2, -9,  2,  1,  6])

In [233]:
np.sqrt(np.sum(np.square(p2-p1)))

15.0

In [234]:
def distance_cal(p1,p2):
    return np.sqrt(np.sum(np.square(p2-p1)))

In [235]:
distance_cal(p1,p2)

15.0