In [3]:
!pip install numpy

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
!pip install --upgrade pip

   ---------------------------------------- 1.8/1.8 MB 28.6 MB/s eta 0:00:00


ERROR: To modify pip, please run the following command:
C:\Users\skme2\anaconda3\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

C:\Users\skme2\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [14]:
# why Numpy?

In [15]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [16]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
%timeit [i**2 for i in lst]

7.86 µs ± 422 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
arr  = np.array(lst)

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [21]:
lst + 2

TypeError: can only concatenate list (not "int") to list

In [22]:
r = []
for i in lst:
    r.append(i+2)

In [23]:
r

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [24]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
%timeit arr**2

1.9 µs ± 80.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [30]:
lst + [1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [32]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
# Numpy Basics

In [34]:
p = [1,5,8,9]

In [35]:
p

[1, 5, 8, 9]

In [37]:
np_arr = np.array(p)

In [38]:
np_arr

array([1, 5, 8, 9])

In [39]:
type(np_arr)

numpy.ndarray

In [40]:
np_arr.ndim

1

In [43]:
np_arr.dtype

dtype('int32')

In [44]:
np_arr.shape

(4,)

In [45]:
np_arr.size

4

In [47]:
v = np.arange(5)

In [48]:
v

array([0, 1, 2, 3, 4])

In [51]:
q = np.arange(5,26,4)

In [52]:
q

array([ 5,  9, 13, 17, 21, 25])

In [53]:
lst_2d = [[1,2,3], [4,5,6], [7,8,9]]

In [54]:
lst_2d


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [56]:
arr_2d = np.array(lst_2d)

In [57]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr_2d.ndim

2

In [60]:
arr_2d.shape

(3, 3)

In [61]:
arr_2d.size

9

In [62]:
# Special Arrays in Numpy

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
np.zeros([6,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [67]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [73]:
np.diag([8,9,10,11,12])

array([[ 8,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0],
       [ 0,  0, 10,  0,  0],
       [ 0,  0,  0, 11,  0],
       [ 0,  0,  0,  0, 12]])

In [77]:
np.diag([4,7,8])

array([[4, 0, 0],
       [0, 7, 0],
       [0, 0, 8]])

In [78]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [79]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
# Indexing in Array

In [84]:
np.random.randint(10,100)

92

In [145]:
new_arr = np.random.randint(0,20,(5,4))

In [146]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [147]:
new_arr.shape

(5, 4)

In [148]:
new_arr.size

20

In [149]:
new_arr.ndim

2

In [150]:
new_arr.dtype

dtype('int32')

In [151]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [152]:
new_arr[0]

array([ 2, 14,  9, 14])

In [153]:
new_arr[1]

array([ 6,  3, 17,  2])

In [154]:
new_arr[-1]

array([ 9,  3,  5, 11])

In [155]:
new_arr[-2]

array([ 7, 15,  9, 19])

In [156]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [157]:
new_arr[:,0]

array([2, 6, 2, 7, 9])

In [158]:
new_arr[:,1]

array([14,  3, 16, 15,  3])

In [159]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [160]:
new_arr[:,-1]

array([14,  2,  5, 19, 11])

In [161]:
new_arr[:,-2]

array([ 9, 17,  3,  9,  5])

In [162]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [163]:
new_arr[:,3]

array([14,  2,  5, 19, 11])

In [164]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [165]:
new_arr[1:3, 1:3]

array([[ 3, 17],
       [16,  3]])

In [166]:
new_arr[:-1]

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19]])

In [167]:
new_arr[0:-2]

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5]])

In [168]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [169]:
new_arr[:,0:-2]

array([[ 2, 14],
       [ 6,  3],
       [ 2, 16],
       [ 7, 15],
       [ 9,  3]])

In [170]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [171]:
new_arr[0][0]

2

In [172]:
new_arr[4][3]

11

In [173]:
#Array Slicing

In [174]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [175]:
new_arr[1:3,0:2]

array([[ 6,  3],
       [ 2, 16]])

In [176]:
new_arr[2:,2:]

array([[ 3,  5],
       [ 9, 19],
       [ 5, 11]])

In [177]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [178]:
new_arr[:,-2]

array([ 9, 17,  3,  9,  5])

In [179]:
new_arr[:,2]

array([ 9, 17,  3,  9,  5])

In [180]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2, 16,  3,  5],
       [ 7, 15,  9, 19],
       [ 9,  3,  5, 11]])

In [181]:
new_arr[-3:-1, -3:-1] = 0

In [182]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2,  0,  0,  5],
       [ 7,  0,  0, 19],
       [ 9,  3,  5, 11]])

In [183]:
new_arr

array([[ 2, 14,  9, 14],
       [ 6,  3, 17,  2],
       [ 2,  0,  0,  5],
       [ 7,  0,  0, 19],
       [ 9,  3,  5, 11]])

In [186]:
new_arr[0][0] = 150

In [187]:
new_arr

array([[150,  14,   9,  14],
       [  6,   3,  17,   2],
       [  2,   0,   0,   5],
       [  7,   0,   0,  19],
       [  9,   3,   5,  11]])

In [188]:
#Masking

In [189]:
new_arr

array([[150,  14,   9,  14],
       [  6,   3,  17,   2],
       [  2,   0,   0,   5],
       [  7,   0,   0,  19],
       [  9,   3,   5,  11]])

In [191]:
mask = new_arr>10

In [192]:
print(mask)

[[ True  True False  True]
 [False False  True False]
 [False False False False]
 [False False False  True]
 [False False False  True]]


In [193]:
np.sum(mask)

6

In [195]:
np.sum(new_arr[mask])

225

In [199]:
np.sum(new_arr<10)

14

In [203]:
np.max(new_arr[new_arr<10])

9

In [204]:
# Basic Operations In Arrays

In [205]:
a = np.array([10,20,30,40])

In [206]:
b = np.arange(1,5)

In [207]:
b

array([1, 2, 3, 4])

In [208]:
a+b

array([11, 22, 33, 44])

In [209]:
a-b

array([ 9, 18, 27, 36])

In [210]:
a*b

array([ 10,  40,  90, 160])

In [211]:
a/b

array([10., 10., 10., 10.])

In [212]:
a//b

array([10, 10, 10, 10])

In [213]:
a%b

array([0, 0, 0, 0])

In [214]:
a**b

array([     10,     400,   27000, 2560000])

In [215]:
b**2

array([ 1,  4,  9, 16])

In [216]:
a

array([10, 20, 30, 40])

In [217]:
a>25

array([False, False,  True,  True])

In [218]:
np.log(15)

2.70805020110221

In [219]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [220]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806])

In [221]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [222]:
# Matrix Product

In [224]:
p = np.random.randint(0,5,(3,4))

In [226]:
q = np.random.randint(0,5,(4,2))

In [227]:
p

array([[1, 0, 3, 2],
       [0, 3, 1, 3],
       [1, 3, 2, 3]])

In [228]:
q

array([[2, 0],
       [0, 4],
       [3, 2],
       [4, 2]])

In [229]:
np.dot(p,q)

array([[19, 10],
       [15, 20],
       [20, 22]])

In [230]:
p*q

ValueError: operands could not be broadcast together with shapes (3,4) (4,2) 

In [231]:
# More Operations on Arrays

In [233]:
s = np.arange(0,24)

In [234]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [235]:
s.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [237]:
s.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [238]:
s.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [239]:
s.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [240]:
s.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [241]:
s.reshape(45,8)

ValueError: cannot reshape array of size 24 into shape (45,8)

In [243]:
T = s.reshape(6,4)

In [244]:
T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [246]:
np.sqrt(T)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [248]:
np.sqrt(T)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [249]:
np.sum(T)

276

In [250]:
np.sum(T, axis=0)

array([60, 66, 72, 78])

In [251]:
np.sum(T, axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [252]:
np.max(T)

23

In [253]:
np.max(T, axis=1)

array([ 3,  7, 11, 15, 19, 23])

In [254]:
np.max(T, axis=0)

array([20, 21, 22, 23])

In [255]:
np.mean(T)

11.5

In [256]:
np.median(T)

11.5

In [257]:
np.std(T)

6.922186552431729

In [258]:
T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [259]:
T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [262]:
T = T.flatten()

In [263]:
T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [265]:
T = T.reshape(3,8)

In [266]:
T

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [267]:
T.T

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [268]:
np.transpose(T)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

# Stacking of Arrays

* Vstack
* Hstack

In [271]:
f = np.random.randint(0,10,(2,2))

In [272]:
f

array([[1, 6],
       [3, 4]])

In [275]:
g = np.random.randint(0,10,(2,2))

In [276]:
f

array([[1, 6],
       [3, 4]])

In [277]:
g

array([[5, 1],
       [9, 8]])

In [278]:
np.hstack((f,g))

array([[1, 6, 5, 1],
       [3, 4, 9, 8]])

In [279]:
np.vstack((f,g))

array([[1, 6],
       [3, 4],
       [5, 1],
       [9, 8]])

In [281]:
# Broadcasting

In [282]:
a

array([10, 20, 30, 40])

In [283]:
a + 5

array([15, 25, 35, 45])

In [285]:
c = np.random.randint(1,15,(3,4))

In [286]:
p

array([[1, 0, 3, 2],
       [0, 3, 1, 3],
       [1, 3, 2, 3]])

In [287]:
c

array([[12, 12, 14, 13],
       [10,  5, 14,  5],
       [12,  2,  3,  5]])

In [288]:
f

array([[1, 6],
       [3, 4]])

In [289]:
c + f

ValueError: operands could not be broadcast together with shapes (3,4) (2,2) 

In [290]:
c + 6


array([[18, 18, 20, 19],
       [16, 11, 20, 11],
       [18,  8,  9, 11]])

In [291]:
f + 8

array([[ 9, 14],
       [11, 12]])

In [292]:
z = np.random.randint(0,10,size = (3,3))

In [293]:
z

array([[4, 3, 1],
       [4, 7, 1],
       [8, 6, 7]])

In [307]:
y = np.array([[1,2,3]])

In [308]:
z

array([[4, 3, 1],
       [4, 7, 1],
       [8, 6, 7]])

In [309]:
y

array([[1, 2, 3]])

In [310]:
print(z.shape)

(3, 3)


In [311]:
print(y.shape)

(1, 3)


In [312]:
z+ y

array([[ 5,  5,  4],
       [ 5,  9,  4],
       [ 9,  8, 10]])

In [313]:
z*y

array([[ 4,  6,  3],
       [ 4, 14,  3],
       [ 8, 12, 21]])

In [314]:
z*y

array([[ 4,  6,  3],
       [ 4, 14,  3],
       [ 8, 12, 21]])

In [315]:
z

array([[4, 3, 1],
       [4, 7, 1],
       [8, 6, 7]])

In [318]:
z + y.T

array([[ 5,  4,  2],
       [ 6,  9,  3],
       [11,  9, 10]])

In [319]:
z

array([[4, 3, 1],
       [4, 7, 1],
       [8, 6, 7]])

In [320]:
z + 6

array([[10,  9,  7],
       [10, 13,  7],
       [14, 12, 13]])

In [322]:
y + 14 

array([[15, 16, 17]])

In [323]:
p1 = [1,2,4,7,-2,9,6,0]

In [324]:
p2 = [5,5,8,2,-9,2,1,6]

In [325]:
p1

[1, 2, 4, 7, -2, 9, 6, 0]

In [326]:
p2

[5, 5, 8, 2, -9, 2, 1, 6]

In [328]:
sum07 = 0
for i in range(len(p1)):
    sum07+=(p2[i]-p1[i])**2

In [331]:
print(sum07**0.5)

15.0


In [332]:
d1 = np.array(p1)

In [333]:
d2 = np.array(p2)

In [334]:
d1

array([ 1,  2,  4,  7, -2,  9,  6,  0])

In [335]:
d2

array([ 5,  5,  8,  2, -9,  2,  1,  6])

In [340]:
def cal_dis(d1,d2):
    return np.sqrt(np.sum(np.square(d2-d1)))

In [341]:
cal_dis(d1,d2)

15.0