In [1]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


In [3]:
diabets = load_diabetes()

In [4]:
diabets

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [12]:
X = diabets.data

In [13]:
y = diabets.target

In [14]:
diabets.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
liner_model = LinearRegression()

In [17]:
liner_model.fit(X_train, y_train)

LinearRegression()

In [18]:
y_pred = liner_model.predict(X_test)

In [20]:
mse = mean_squared_error(y_test, y_pred)

In [21]:
r2 = r2_score(y_test, y_pred)

In [22]:
print("MSE is : ", mse)
print("R2 score is :", r2)

MSE is :  2900.1732878832318
R2 score is : 0.45260660216173787


In [28]:
# LOgistic Regression

In [29]:
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [32]:
breast_cancer_dataset = load_breast_cancer()

In [33]:
X = breast_cancer_dataset.data

In [34]:
y = breast_cancer_dataset.target

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
logistic_model = LogisticRegression(max_iter=10000)

In [38]:
logistic_model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [39]:
y_pred = logistic_model.predict(X_test)

In [40]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

In [41]:
print("Accuracy : ", accuracy)
print("Precision : ", precision)
print('f1 : ', f1)
print("recall : ", recall)

Accuracy :  0.956140350877193
Precision :  0.9459459459459459
f1 :  0.9655172413793103
recall :  0.9859154929577465


In [42]:
# Decision Tree

In [43]:
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, accuracy_score, recall_score, f1_score


In [45]:
winev = load_wine()

In [46]:
X = winev.data

In [47]:
y = winev.target

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [49]:
decision_model = DecisionTreeClassifier(random_state=42)

In [50]:
decision_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [51]:
y_pred = decision_model.predict(X_test)

In [54]:
y_test

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0])

In [55]:
y_pred

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0])

In [57]:
winev.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [64]:
print("Precision Score : ",precision_score(y_test, y_pred, average='micro'))

Precision Score :  0.9444444444444444


In [63]:
print("Recall Score : ",recall_score(y_test, y_pred,average='micro'))

Recall Score :  0.9444444444444444


In [74]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy : ", accuracy)

Accuracy :  0.9444444444444444


In [75]:
f1 = f1_score(y_test, y_pred, average='micro')
print("F1 score : ", f1)

F1 score :  0.9444444444444444


In [76]:
# naive bayes

In [77]:
from sklearn.datasets import load_digits
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, r2_score, recall_score
from sklearn.model_selection import train_test_split

In [78]:
digits = load_digits()

In [79]:
X, y  = digits.data, digits.target

In [80]:
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [81]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [83]:
naivebayes_model = GaussianNB()

In [84]:
naivebayes_model.fit(X_train, y_train)

GaussianNB()

In [85]:
y_pred = naivebayes_model.predict(X_test)

In [86]:
print("Precision Score : ",precision_score(y_test, y_pred, average='macro'))
print("Recall Score : ",recall_score(y_test, y_pred,average='macro'))
f1 = f1_score(y_test, y_pred, average='macro')
print("F1 score : ", f1)


Precision Score :  0.8649844547206135
Recall Score :  0.8476479221745045
F1 score :  0.8437352605469787


In [87]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy : ", accuracy)

Accuracy :  0.8472222222222222


In [88]:
#KNN

In [89]:
from sklearn.datasets import load_wine
from sklearn.neighbors import KNeighborsClassifier


In [90]:
wine = load_wine()

In [91]:
X = wine.data

In [92]:
y = wine.target

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [94]:
knn_model = KNeighborsClassifier(n_neighbors=3)

In [95]:
knn_model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [96]:
y_pred = knn_model.predict(X_test)

In [97]:
print("Precision Score : ",precision_score(y_test, y_pred, average='macro'))
print("Recall Score : ",recall_score(y_test, y_pred,average='macro'))
f1 = f1_score(y_test, y_pred, average='macro')
print("F1 score : ", f1)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy : ", accuracy)

Precision Score :  0.7912698412698412
Recall Score :  0.7976190476190476
F1 score :  0.7899877899877898
Accuracy :  0.8055555555555556


In [98]:
# SVM

In [99]:
from sklearn.svm import SVC

In [100]:
X = breast_cancer_dataset.data

In [101]:
y = breast_cancer_dataset.target

In [102]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [103]:
svc_model = SVC()

In [104]:
svc_model.fit(X_train, y_train)

SVC()

In [105]:
y_pred = svc_model.predict(X_test)

In [106]:
print("Precision Score : ",precision_score(y_test, y_pred, average='macro'))
print("Recall Score : ",recall_score(y_test, y_pred,average='macro'))
f1 = f1_score(y_test, y_pred, average='macro')
print("F1 score : ", f1)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy : ", accuracy)

Precision Score :  0.961038961038961
Recall Score :  0.9302325581395349
F1 score :  0.9422297297297297
Accuracy :  0.9473684210526315


In [107]:
#random Fotrest

In [108]:
from sklearn.ensemble import RandomForestClassifier

In [109]:
X = breast_cancer_dataset.data

In [110]:
y = breast_cancer_dataset.target

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [112]:
rf_model = RandomForestClassifier()

In [113]:
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [114]:
y_pred = rf_model.predict(X_test)

In [115]:
print("Precision Score : ",precision_score(y_test, y_pred, average='macro'))
print("Recall Score : ",recall_score(y_test, y_pred,average='macro'))
f1 = f1_score(y_test, y_pred, average='macro')
print("F1 score : ", f1)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy : ", accuracy)

Precision Score :  0.9672569328433009
Recall Score :  0.9580740255486406
F1 score :  0.9623015873015873
Accuracy :  0.9649122807017544


In [116]:
# K-means- Clustring

In [117]:
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
from sklearn.metrics import silhouette_score

In [119]:
iris = load_iris()

In [120]:
X = iris.data

In [121]:
kmeans_model = KMeans(n_clusters=3, random_state=42)

In [123]:
kmeans_model.fit(X)

KMeans(n_clusters=3, random_state=42)

In [124]:
y_pred_clusters = kmeans_model.predict(X)

In [126]:
inertia = kmeans_model.inertia_
silhouette =  silhouette_score(X, y_pred_clusters)

In [127]:
print("Inertia : ", inertia)
print("Silhouette :", silhouette)

Inertia :  78.851441426146
Silhouette : 0.5528190123564094


In [128]:
# PCA

In [129]:
from sklearn.decomposition import PCA
import numpy as np

In [130]:
X = breast_cancer_dataset.data

In [131]:
pca = PCA(n_components=2)

In [132]:
pca.fit(X)

PCA(n_components=2)

In [133]:
X_pca = pca.transform(X)

In [140]:
explained_variance = pca.explained_variance_ratio_

In [141]:
total_explained_variance = np.sum(explained_variance)

In [142]:
print("Explained_variance : ", explained_variance)
print("Total explained_variance : ", total_explained_variance)

Explained_variance :  [0.98204467 0.01617649]
Total explained_variance :  0.9982211613741716


In [143]:
pca.explained_variance_ratio_

array([0.98204467, 0.01617649])

In [144]:

# Gradient Boosting

In [145]:
from sklearn.datasets import load_diabetes
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [146]:
diabetes= load_diabetes()

In [147]:
X = diabetes.data

In [148]:
y = diabetes.target

In [149]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [150]:
gb_model = GradientBoostingRegressor(random_state=42)

In [151]:
gb_model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [153]:
y_pred_gb = gb_model.predict(X_test)

In [154]:
mse_gb = mean_squared_error(y_test, y_pred_gb)

In [155]:
r2_gb = r2_score(y_test, y_pred_gb)

In [156]:
print("MSE : ", mse_gb)
print("R2 score : ", r2_gb)

MSE :  2906.4600940881232
R2 score :  0.45141999851138914
