##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

Current Numpy version : 1.19.2


In [99]:
## write code here


In [1]:
import numpy as np

C:\Users\skme2\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
print("Version : ",np.__version__)

Version :  1.22.4


#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
## write code here


In [16]:
arr = np.arange(1,17)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

[ 1  3  5  7  9 11 13 15]


In [ ]:
## write code here


In [10]:
filtered_array = arr[arr%2!=0]
print(filtered_array)

[ 1  3  5  7  9 11 13 15]


#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0]


In [ ]:
## write code here


In [17]:
arr[arr%2==0] = 0

In [18]:
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0])

#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [ ]:
## write code here


In [19]:
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0])

In [21]:
arr = arr.reshape(4,4)
print(arr)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

In [23]:
new_arr = np.vstack([arr,arr])

In [24]:
print(new_arr)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]
 [ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [23]:
## write code here


#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

[[ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]
 [ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]]


In [33]:
## write code here


In [25]:
new_arr

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

In [27]:
new_arr = new_arr[:,[1,0,3,2]]

In [28]:
print(new_arr)

[[ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]
 [ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]]


#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

Mean : 4.0
Median : 0.5
Mode : 0


In [ ]:
## write code here


In [29]:
import statistics


In [32]:
print("Mean:",np.mean(new_arr))

Mean: 4.0


In [34]:
print("Median :",np.median(new_arr))

Median : 0.5


In [37]:
print("Mode :",statistics.mode(new_arr.flatten()))

Mode : 0


#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

Random Element Array : [15  0  5  3  0]


In [ ]:
## write code here


In [48]:
new_arr = np.array([np.random.choice(new_arr.flatten()) for i in range(5)])

In [49]:
print("Random array :", new_arr)

Random array : [13  3 13  0  0]


#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [94]:
def BCE(y, y_hat):
    ## write code here
    

In [50]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

NameError: name 'BCE' is not defined

In [54]:
def BCE(y, y_hat):
    return  np.mean(y*np.log2(y_hat) - (1-y)*np.log2(1-y_hat))

In [55]:
BCE(y, y_hat)

0.011179895048277702