In [1]:
!pip install numpy

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!pip install --upgrade pip

   ---------------------------------------- 2.1/2.1 MB 16.8 MB/s eta 0:00:00


ERROR: To modify pip, please run the following command:
C:\Users\skme2\anaconda3\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

C:\Users\skme2\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [5]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [8]:
x = []
for i in lst:
    x.append(i+1)

In [9]:
x

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [11]:
%timeit [i**2 for i in lst]

2.3 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
arr = np.array(lst)

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
%timeit arr**2

430 ns ± 24.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
lst + 1

TypeError: can only concatenate list (not "int") to list

In [21]:
lst + [1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [23]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
k = [4,5,6,7,8,9]

In [25]:
type(k)

list

In [27]:
g  =np.array(k)

In [28]:
type(g)

numpy.ndarray

In [29]:
g

array([4, 5, 6, 7, 8, 9])

In [30]:
g.ndim

1

In [31]:
g.shape

(6,)

In [37]:
s = np.arange(1,20,2)

In [38]:
type(s)

numpy.ndarray

In [39]:
s

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
s.ndim

1

In [41]:
s.shape

(10,)

In [42]:
lst_2d  =[[1,2,3], [4,5,6], [7,8,9]]

In [43]:
lst_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [44]:
type(lst_2d)

list

In [46]:
arr1 = np.array(lst_2d)

In [47]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
type(arr1)

numpy.ndarray

In [49]:
arr1.ndim

2

In [50]:
arr1.shape

(3, 3)

In [51]:
arr1.nbytes

36

In [53]:
arr1.nonzero()

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [54]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr1.dtype

dtype('int32')

In [56]:
# Special Arrays in Numpy

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((8,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [60]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [62]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [66]:
np.diag([5])

array([[5]])

In [70]:
np.diag([4,8,9,10], k= 3)

array([[ 0,  0,  0,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0, 10],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [74]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [75]:
# indexing in Array

In [80]:
np.random.randint(10,100)

18

In [82]:
new_arr = np.random.randint(10, 100, (6,8))

In [83]:
new_arr.shape

(6, 8)

In [84]:
new_arr.ndim

2

In [85]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72, 74, 42, 84, 17, 16],
       [65, 77, 32, 16, 14, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [87]:
new_arr[0]

array([11, 15, 37, 40, 30, 45, 42, 16])

In [88]:
new_arr[1]

array([17, 89, 32, 58, 53, 80, 41, 91])

In [89]:
new_arr[2]

array([58, 78, 72, 74, 42, 84, 17, 16])

In [91]:
new_arr[-1]

array([63, 89, 71, 28, 37, 49, 99, 96])

In [92]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72, 74, 42, 84, 17, 16],
       [65, 77, 32, 16, 14, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [93]:
new_arr[-2]

array([16, 83, 68, 60, 68, 63, 86, 36])

In [94]:
new_arr[:,0]

array([11, 17, 58, 65, 16, 63])

In [95]:
new_arr[:,1]

array([15, 89, 78, 77, 83, 89])

In [96]:
new_arr[:,-1]

array([16, 91, 16, 45, 36, 96])

In [97]:
new_arr[:,-2]

array([42, 41, 17, 24, 86, 99])

In [98]:
new_arr


array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72, 74, 42, 84, 17, 16],
       [65, 77, 32, 16, 14, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [99]:
new_arr[0,0]

11

In [100]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72, 74, 42, 84, 17, 16],
       [65, 77, 32, 16, 14, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [101]:
new_arr[0:2,0:2]

array([[11, 15],
       [17, 89]])

In [103]:
new_arr[4:, 6:]

array([[86, 36],
       [99, 96]])

In [104]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72, 74, 42, 84, 17, 16],
       [65, 77, 32, 16, 14, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [106]:
new_arr[-2:, -2:]

array([[86, 36],
       [99, 96]])

In [108]:
new_arr[3, 3]

16

In [109]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72, 74, 42, 84, 17, 16],
       [65, 77, 32, 16, 14, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [110]:

new_arr[:, -1]

array([16, 91, 16, 45, 36, 96])

In [111]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72, 74, 42, 84, 17, 16],
       [65, 77, 32, 16, 14, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [114]:
new_arr[2:4, 3:5] = 0

In [115]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72,  0,  0, 84, 17, 16],
       [65, 77, 32,  0,  0, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [116]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72,  0,  0, 84, 17, 16],
       [65, 77, 32,  0,  0, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [117]:
# masking

In [118]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72,  0,  0, 84, 17, 16],
       [65, 77, 32,  0,  0, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [120]:

new_arr>50

array([[False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True],
       [ True,  True,  True, False, False,  True, False, False],
       [ True,  True, False, False, False,  True, False, False],
       [False,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True, False, False, False,  True,  True]])

In [122]:
new_arr[new_arr>50]

array([89, 58, 53, 80, 91, 58, 78, 72, 84, 65, 77, 67, 83, 68, 60, 68, 63,
       86, 63, 89, 71, 99, 96])

In [125]:
np.sum(new_arr>50)

23

In [128]:
new_arr[new_arr>50]

array([89, 58, 53, 80, 91, 58, 78, 72, 84, 65, 77, 67, 83, 68, 60, 68, 63,
       86, 63, 89, 71, 99, 96])

In [131]:
new_arr[~(new_arr>50)]

array([11, 15, 37, 40, 30, 45, 42, 16, 17, 32, 41,  0,  0, 17, 16, 32,  0,
        0, 24, 45, 16, 36, 28, 37, 49])

In [132]:
new_arr

array([[11, 15, 37, 40, 30, 45, 42, 16],
       [17, 89, 32, 58, 53, 80, 41, 91],
       [58, 78, 72,  0,  0, 84, 17, 16],
       [65, 77, 32,  0,  0, 67, 24, 45],
       [16, 83, 68, 60, 68, 63, 86, 36],
       [63, 89, 71, 28, 37, 49, 99, 96]])

In [133]:
# Basic Operations in Arrays

In [134]:
a = np.array([10,20,30,40])

In [135]:
b = np.arange(1,5)

In [136]:
a

array([10, 20, 30, 40])

In [137]:
b

array([1, 2, 3, 4])

In [138]:
a+b

array([11, 22, 33, 44])

In [139]:
a-b

array([ 9, 18, 27, 36])

In [140]:
a*b

array([ 10,  40,  90, 160])

In [141]:
a/b

array([10., 10., 10., 10.])

In [142]:
b**2

array([ 1,  4,  9, 16])

In [143]:
a**3

array([ 1000,  8000, 27000, 64000], dtype=int32)

In [144]:
a>15

array([False,  True,  True,  True])

In [145]:
a[a>15]

array([20, 30, 40])

In [149]:
a[~(a>15)]

array([10])

In [150]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [151]:
np.sin(b)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [152]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806])

In [153]:
# matrix product

In [154]:
p = np.random.randint(0,5,(3,4))

In [155]:
q = np.random.randint(0,5,(4,5))

In [156]:
p

array([[0, 2, 0, 3],
       [1, 0, 0, 4],
       [2, 3, 4, 0]])

In [157]:
q

array([[2, 2, 2, 4, 1],
       [1, 3, 0, 2, 0],
       [1, 4, 2, 3, 4],
       [1, 1, 1, 2, 4]])

In [158]:
np.dot(p,q)

array([[ 5,  9,  3, 10, 12],
       [ 6,  6,  6, 12, 17],
       [11, 29, 12, 26, 18]])

In [159]:
p * q

ValueError: operands could not be broadcast together with shapes (3,4) (4,5) 

In [160]:
d  =np.random.randint(0,5,(2,2))

In [161]:
c = np.random.randint(0,5,(2,2))

In [162]:
d

array([[2, 1],
       [4, 1]])

In [163]:
c

array([[2, 3],
       [1, 2]])

In [164]:
np.dot(d,c)

array([[ 5,  8],
       [ 9, 14]])

In [165]:
d*c

array([[4, 3],
       [4, 2]])

In [166]:
# More Operations on Arrays

In [167]:
z  =np.arange(0,24)

In [168]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [169]:
z.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [171]:
z.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [172]:
z.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [173]:
z.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [175]:
z = z.reshape(4,6)

In [176]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [177]:
np.sqrt(z)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563],
       [4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152]])

In [178]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [179]:
np.sum(z)

276

In [183]:
np.sum(z,axis=-1 )

array([ 15,  51,  87, 123])

In [184]:
np.sum(z,0)

array([36, 40, 44, 48, 52, 56])

In [185]:
np.sum(z, axis=1)

array([ 15,  51,  87, 123])

In [186]:
np.min(z)

0

In [187]:
np.min(z, axis=0)

array([0, 1, 2, 3, 4, 5])

In [188]:
np.min(z, axis=1)

array([ 0,  6, 12, 18])

In [189]:
np.average(z)

11.5

In [190]:
np.average(z, axis=0)

array([ 9., 10., 11., 12., 13., 14.])

In [191]:
np.average(z, axis=1)

array([ 2.5,  8.5, 14.5, 20.5])

In [192]:
np.std(z)

6.922186552431729

In [193]:
np.std(z, axis=0)

array([6.70820393, 6.70820393, 6.70820393, 6.70820393, 6.70820393,
       6.70820393])

In [194]:
np.std(z, axis=1)

array([1.70782513, 1.70782513, 1.70782513, 1.70782513])

In [195]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [196]:
z.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [197]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [198]:
z.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [199]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [200]:
z.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [202]:
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [204]:
np.transpose(z)

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [205]:
# Stacking of Arrays

In [206]:
m = np.random.randint(0,10, (2,2))

In [207]:
m

array([[9, 2],
       [7, 8]])

In [208]:
n = np.random.randint(0,10, (2,2))

In [209]:
n

array([[2, 3],
       [4, 6]])

In [211]:
np.hstack((m,n))

array([[9, 2, 2, 3],
       [7, 8, 4, 6]])

In [214]:
np.vstack((m,n))

array([[9, 2],
       [7, 8],
       [2, 3],
       [4, 6]])

In [215]:
A = np.random.randint(0,10,size = (3,3))

In [216]:
A

array([[3, 2, 5],
       [2, 4, 4],
       [7, 9, 2]])

In [222]:
B = np.array([[1,2,3]])

In [223]:
B

array([[1, 2, 3]])

In [224]:
A.shape

(3, 3)

In [225]:
B.shape

(1, 3)

In [226]:
A + B

array([[ 4,  4,  8],
       [ 3,  6,  7],
       [ 8, 11,  5]])

In [227]:
A.T

array([[3, 2, 7],
       [2, 4, 9],
       [5, 4, 2]])

In [228]:
B + A.T

array([[ 4,  4, 10],
       [ 3,  6, 12],
       [ 6,  6,  5]])

In [229]:
A

array([[3, 2, 5],
       [2, 4, 4],
       [7, 9, 2]])

In [230]:
A + 5

array([[ 8,  7, 10],
       [ 7,  9,  9],
       [12, 14,  7]])

In [231]:
A * 3

array([[ 9,  6, 15],
       [ 6, 12, 12],
       [21, 27,  6]])

In [232]:
# vectorizations

In [233]:
p1 = np.array([1,2,4,7,-2,9,6,0])

In [234]:
p2 = np.array([5,5,8,2,-9,2,1,6])

In [235]:
p1

array([ 1,  2,  4,  7, -2,  9,  6,  0])

In [236]:
p2

array([ 5,  5,  8,  2, -9,  2,  1,  6])

In [237]:
sum_12 = 0
for i in range(len(p1)):
    sum_12+=(p2[i]-p1[i])**2

In [238]:
sum_12

225

In [240]:
sum_12**0.5

15.0

In [241]:
p1

array([ 1,  2,  4,  7, -2,  9,  6,  0])

In [242]:
p2

array([ 5,  5,  8,  2, -9,  2,  1,  6])

In [248]:
def distance(p1,p2):
    return np.sqrt(np.sum(np.square(p2-p1)))

In [249]:
distance(p1,p2)

15.0

In [250]:
# pandas

In [251]:
!pip install pandas

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [252]:
import pandas as pd

In [253]:
w = ['Python', 'javaScript', 'c', 'c++', 'HTML', 'CSS']

In [254]:
w

['Python', 'javaScript', 'c', 'c++', 'HTML', 'CSS']

In [255]:
type(w)

list

In [257]:
ser = pd.Series(w)

In [258]:
ser

0        Python
1    javaScript
2             c
3           c++
4          HTML
5           CSS
dtype: object

In [259]:
type(ser)

pandas.core.series.Series

In [261]:
ser[2]

'c'

In [262]:
ser[1]

'javaScript'

In [264]:
ser[4]

'HTML'

In [266]:
ser.index = ['A', "B", 'C', 'D', 'E', 'F']

In [267]:
ser

A        Python
B    javaScript
C             c
D           c++
E          HTML
F           CSS
dtype: object

In [268]:
ser['A']

'Python'

In [271]:
ser['E']

'HTML'

In [273]:
ser[4]

'HTML'

In [274]:
import numpy as np

In [279]:
arr = np.random.randint(10,100, size = (8,6))

In [281]:
df = pd.DataFrame(arr)

In [282]:
df

0   1   2   3   4   5
0  51  53  72  45  92  71
1  49  18  19  80  51  78
2  55  73  34  38  58  32
3  36  25  40  87  64  19
4  10  47  70  20  39  54
5  55  57  21  52  37  97
6  21  57  22  14  31  35
7  78  40  62  56  95  30

In [283]:
type(df)

pandas.core.frame.DataFrame

In [285]:
df[2]

0    72
1    19
2    34
3    40
4    70
5    21
6    22
7    62
Name: 2, dtype: int32

In [287]:
df[1]

0    53
1    18
2    73
3    25
4    47
5    57
6    57
7    40
Name: 1, dtype: int32

In [290]:
df[0]

0    51
1    49
2    55
3    36
4    10
5    55
6    21
7    78
Name: 0, dtype: int32

In [294]:
df[5]

0    71
1    78
2    32
3    19
4    54
5    97
6    35
7    30
Name: 5, dtype: int32

In [296]:
df.loc[0]

0    51
1    53
2    72
3    45
4    92
5    71
Name: 0, dtype: int32

In [297]:
df

0   1   2   3   4   5
0  51  53  72  45  92  71
1  49  18  19  80  51  78
2  55  73  34  38  58  32
3  36  25  40  87  64  19
4  10  47  70  20  39  54
5  55  57  21  52  37  97
6  21  57  22  14  31  35
7  78  40  62  56  95  30

In [298]:
df.loc[2]

0    55
1    73
2    34
3    38
4    58
5    32
Name: 2, dtype: int32

In [299]:
df

0   1   2   3   4   5
0  51  53  72  45  92  71
1  49  18  19  80  51  78
2  55  73  34  38  58  32
3  36  25  40  87  64  19
4  10  47  70  20  39  54
5  55  57  21  52  37  97
6  21  57  22  14  31  35
7  78  40  62  56  95  30

In [300]:
df.iloc[1]

0    49
1    18
2    19
3    80
4    51
5    78
Name: 1, dtype: int32

In [302]:
df

0   1   2   3   4   5
0  51  53  72  45  92  71
1  49  18  19  80  51  78
2  55  73  34  38  58  32
3  36  25  40  87  64  19
4  10  47  70  20  39  54
5  55  57  21  52  37  97
6  21  57  22  14  31  35
7  78  40  62  56  95  30

In [303]:
df.loc[:,5]

0    71
1    78
2    32
3    19
4    54
5    97
6    35
7    30
Name: 5, dtype: int32

In [305]:
df.index = "a b c d e f g h".split()

In [306]:
df

0   1   2   3   4   5
a  51  53  72  45  92  71
b  49  18  19  80  51  78
c  55  73  34  38  58  32
d  36  25  40  87  64  19
e  10  47  70  20  39  54
f  55  57  21  52  37  97
g  21  57  22  14  31  35
h  78  40  62  56  95  30

In [309]:
df.columns = ['p', 'q', 'r', 's', 't', 'u']

In [310]:
df

p   q   r   s   t   u
a  51  53  72  45  92  71
b  49  18  19  80  51  78
c  55  73  34  38  58  32
d  36  25  40  87  64  19
e  10  47  70  20  39  54
f  55  57  21  52  37  97
g  21  57  22  14  31  35
h  78  40  62  56  95  30

In [312]:
df[5]

KeyError: 5

In [314]:
df[2]

KeyError: 2

In [316]:
df['q']

a    53
b    18
c    73
d    25
e    47
f    57
g    57
h    40
Name: q, dtype: int32

In [318]:
df['s']

a    45
b    80
c    38
d    87
e    20
f    52
g    14
h    56
Name: s, dtype: int32

In [320]:
df.loc[2]

KeyError: 2

In [321]:
df.iloc[2]

p    55
q    73
r    34
s    38
t    58
u    32
Name: c, dtype: int32

In [322]:
df

p   q   r   s   t   u
a  51  53  72  45  92  71
b  49  18  19  80  51  78
c  55  73  34  38  58  32
d  36  25  40  87  64  19
e  10  47  70  20  39  54
f  55  57  21  52  37  97
g  21  57  22  14  31  35
h  78  40  62  56  95  30

In [323]:
df.loc['c']

p    55
q    73
r    34
s    38
t    58
u    32
Name: c, dtype: int32

In [325]:
df.iloc[3:5,2:4]

r   s
d  40  87
e  70  20

In [326]:
df

p   q   r   s   t   u
a  51  53  72  45  92  71
b  49  18  19  80  51  78
c  55  73  34  38  58  32
d  36  25  40  87  64  19
e  10  47  70  20  39  54
f  55  57  21  52  37  97
g  21  57  22  14  31  35
h  78  40  62  56  95  30

In [328]:
df.iloc[0,0]

51

In [329]:
df.shape

(8, 6)

In [330]:
df.head()

p   q   r   s   t   u
a  51  53  72  45  92  71
b  49  18  19  80  51  78
c  55  73  34  38  58  32
d  36  25  40  87  64  19
e  10  47  70  20  39  54

In [331]:
df.head(2)

p   q   r   s   t   u
a  51  53  72  45  92  71
b  49  18  19  80  51  78

In [332]:
df.tail()

p   q   r   s   t   u
d  36  25  40  87  64  19
e  10  47  70  20  39  54
f  55  57  21  52  37  97
g  21  57  22  14  31  35
h  78  40  62  56  95  30

In [333]:
df.tail(3)

p   q   r   s   t   u
f  55  57  21  52  37  97
g  21  57  22  14  31  35
h  78  40  62  56  95  30

In [338]:
df.sample(2)

p   q   r   s   t   u
d  36  25  40  87  64  19
f  55  57  21  52  37  97

In [342]:
df[['r', 's']]

r   s
a  72  45
b  19  80
c  34  38
d  40  87
e  70  20
f  21  52
g  22  14
h  62  56

In [344]:
df[['t', 'q', 'r']]

t   q   r
a  92  53  72
b  51  18  19
c  58  73  34
d  64  25  40
e  39  47  70
f  37  57  21
g  31  57  22
h  95  40  62

In [345]:
df

p   q   r   s   t   u
a  51  53  72  45  92  71
b  49  18  19  80  51  78
c  55  73  34  38  58  32
d  36  25  40  87  64  19
e  10  47  70  20  39  54
f  55  57  21  52  37  97
g  21  57  22  14  31  35
h  78  40  62  56  95  30

In [349]:
df['v'] =  df['p'] + 5

In [350]:
df

p   q   r   s   t   u   v
a  51  53  72  45  92  71  56
b  49  18  19  80  51  78  54
c  55  73  34  38  58  32  60
d  36  25  40  87  64  19  41
e  10  47  70  20  39  54  15
f  55  57  21  52  37  97  60
g  21  57  22  14  31  35  26
h  78  40  62  56  95  30  83

In [351]:
df['s']

a    45
b    80
c    38
d    87
e    20
f    52
g    14
h    56
Name: s, dtype: int32

In [352]:
df['t']

a    92
b    51
c    58
d    64
e    39
f    37
g    31
h    95
Name: t, dtype: int32

In [356]:
df['w'] = df['s'] + df['t']

In [357]:
df

p   q   r   s   t   u   v    w
a  51  53  72  45  92  71  56  137
b  49  18  19  80  51  78  54  131
c  55  73  34  38  58  32  60   96
d  36  25  40  87  64  19  41  151
e  10  47  70  20  39  54  15   59
f  55  57  21  52  37  97  60   89
g  21  57  22  14  31  35  26   45
h  78  40  62  56  95  30  83  151

In [359]:
df['x'] = 5

In [360]:
df

p   q   r   s   t   u   v    w  x
a  51  53  72  45  92  71  56  137  5
b  49  18  19  80  51  78  54  131  5
c  55  73  34  38  58  32  60   96  5
d  36  25  40  87  64  19  41  151  5
e  10  47  70  20  39  54  15   59  5
f  55  57  21  52  37  97  60   89  5
g  21  57  22  14  31  35  26   45  5
h  78  40  62  56  95  30  83  151  5

In [365]:
df.drop('v',axis=1, inplace=True )

In [366]:
df

p   q   r   s   t   u    w  x
a  51  53  72  45  92  71  137  5
b  49  18  19  80  51  78  131  5
c  55  73  34  38  58  32   96  5
d  36  25  40  87  64  19  151  5
e  10  47  70  20  39  54   59  5
f  55  57  21  52  37  97   89  5
g  21  57  22  14  31  35   45  5
h  78  40  62  56  95  30  151  5

In [373]:
df = df.drop(labels=['w', 'x'], axis=1)

In [374]:
df

p   q   r   s   t   u
a  51  53  72  45  92  71
b  49  18  19  80  51  78
c  55  73  34  38  58  32
d  36  25  40  87  64  19
e  10  47  70  20  39  54
f  55  57  21  52  37  97
g  21  57  22  14  31  35
h  78  40  62  56  95  30

In [376]:
df.drop(columns=['s', 't'], axis=1, inplace=True)

In [377]:
df

p   q   r   u
a  51  53  72  71
b  49  18  19  78
c  55  73  34  32
d  36  25  40  19
e  10  47  70  54
f  55  57  21  97
g  21  57  22  35
h  78  40  62  30

In [378]:
df

p   q   r   u
a  51  53  72  71
b  49  18  19  78
c  55  73  34  32
d  36  25  40  19
e  10  47  70  54
f  55  57  21  97
g  21  57  22  35
h  78  40  62  30

In [382]:
df.iloc[-2:][['p', 'q']]

p   q
g  21  57
h  78  40

In [383]:
df

p   q   r   u
a  51  53  72  71
b  49  18  19  78
c  55  73  34  32
d  36  25  40  19
e  10  47  70  54
f  55  57  21  97
g  21  57  22  35
h  78  40  62  30

In [386]:
df.iloc[-2:, -2:] = 0

In [387]:
df

p   q   r   u
a  51  53  72  71
b  49  18  19  78
c  55  73  34  32
d  36  25  40  19
e  10  47  70  54
f  55  57  21  97
g  21  57   0   0
h  78  40   0   0

In [388]:
# Masking or Boolean Indexing

In [389]:

df

p   q   r   u
a  51  53  72  71
b  49  18  19  78
c  55  73  34  32
d  36  25  40  19
e  10  47  70  54
f  55  57  21  97
g  21  57   0   0
h  78  40   0   0

In [390]:
df>50

p      q      r      u
a   True   True   True   True
b  False  False  False   True
c   True   True  False  False
d  False  False  False  False
e  False  False   True   True
f   True   True  False   True
g  False   True  False  False
h   True  False  False  False

In [392]:
df[df>50]

p     q     r     u
a  51.0  53.0  72.0  71.0
b   NaN   NaN   NaN  78.0
c  55.0  73.0   NaN   NaN
d   NaN   NaN   NaN   NaN
e   NaN   NaN  70.0  54.0
f  55.0  57.0   NaN  97.0
g   NaN  57.0   NaN   NaN
h  78.0   NaN   NaN   NaN

In [393]:
df[~(df>50)]

p     q     r     u
a   NaN   NaN   NaN   NaN
b  49.0  18.0  19.0   NaN
c   NaN   NaN  34.0  32.0
d  36.0  25.0  40.0  19.0
e  10.0  47.0   NaN   NaN
f   NaN   NaN  21.0   NaN
g  21.0   NaN   0.0   0.0
h   NaN  40.0   0.0   0.0

In [395]:
df[df>30]

p     q     r     u
a  51.0  53.0  72.0  71.0
b  49.0   NaN   NaN  78.0
c  55.0  73.0  34.0  32.0
d  36.0   NaN  40.0   NaN
e   NaN  47.0  70.0  54.0
f  55.0  57.0   NaN  97.0
g   NaN  57.0   NaN   NaN
h  78.0  40.0   NaN   NaN

In [396]:
df[~(df>30)]

p     q     r     u
a   NaN   NaN   NaN   NaN
b   NaN  18.0  19.0   NaN
c   NaN   NaN   NaN   NaN
d   NaN  25.0   NaN  19.0
e  10.0   NaN   NaN   NaN
f   NaN   NaN  21.0   NaN
g  21.0   NaN   0.0   0.0
h   NaN   NaN   0.0   0.0

In [400]:
df[df['p']>20]

p   q   r   u
a  51  53  72  71
b  49  18  19  78
c  55  73  34  32
d  36  25  40  19
f  55  57  21  97
g  21  57   0   0
h  78  40   0   0

In [407]:
df[df['q']>30][['p','q']]

p   q
a  51  53
c  55  73
e  10  47
f  55  57
g  21  57
h  78  40

In [414]:
df['r']<50

a    False
b     True
c     True
d     True
e    False
f     True
g     True
h     True
Name: r, dtype: bool

In [415]:
df['u']>40

a     True
b     True
c    False
d    False
e     True
f     True
g    False
h    False
Name: u, dtype: bool

In [417]:
df[(df['r']<50) & (df['u']>40)]

p   q   r   u
b  49  18  19  78
f  55  57  21  97

In [418]:
df

p   q   r   u
a  51  53  72  71
b  49  18  19  78
c  55  73  34  32
d  36  25  40  19
e  10  47  70  54
f  55  57  21  97
g  21  57   0   0
h  78  40   0   0

In [420]:
arr = df.values

In [421]:
arr

array([[51, 53, 72, 71],
       [49, 18, 19, 78],
       [55, 73, 34, 32],
       [36, 25, 40, 19],
       [10, 47, 70, 54],
       [55, 57, 21, 97],
       [21, 57,  0,  0],
       [78, 40,  0,  0]])

In [422]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [423]:
ls

 Volume in drive C is OS
 Volume Serial Number is 0CC1-C20F

 Directory of C:\Users\skme2\Downloads

12-02-2024  23:34    <DIR>          .
12-02-2024  18:58    <DIR>          ..
12-02-2024  23:02    <DIR>          .ipynb_checkpoints
21-12-2023  11:58    <DIR>          __pycache__
06-11-2023  11:20             2,633 01_11_sql_practice.sql
02-11-2022  15:49           410,816 0211resume.pdf
03-09-2023  14:20            54,756 03_09_1_pm_Functions.ipynb
13-10-2023  15:25    <DIR>          03_10_4pm
13-10-2023  15:24        98,232,624 03_10_4pm.zip
20-03-2023  16:51           118,844 04_06.ipynb
13-10-2023  15:24    <DIR>          04_10_4pm
13-10-2023  15:23        85,733,531 04_10_4pm.zip
04-12-2023  16:36               185 04_12_03_05_pm.sql
05-12-2023  11:43            78,452 04_12_python_class_2.ipynb
05-08-2023  17:33       144,122,096 05_08_1PM.zip
05-08-2023  17:32            28,266 05_08_firoj_tapan.ipynb
05-12-2023  17:47             1,293 05_12_03_05_pm.sql
06-12-2023  12:35      

24-04-2023  13:01           375,712 22b01038ed616ac43165687bedaaee45ee8fbebc93c75e197f48c529c415222e-2023-04-24-07-31-10.zip
30-08-2023  20:49           114,114 22b01038ed616ac43165687bedaaee45ee8fbebc93c75e197f48c529c415222e-2023-08-30-15-19-02.zip
07-09-2023  10:31    <DIR>          22b01038ed616ac43165687bedaaee45ee8fbebc93c75e197f48c529c415222e-2023-09-07-05-00-53
07-09-2023  10:31           132,147 22b01038ed616ac43165687bedaaee45ee8fbebc93c75e197f48c529c415222e-2023-09-07-05-00-53.zip
03-07-2022  11:53    <DIR>          22ndmay-20220702T055801Z-001
10-09-2022  23:12    <DIR>          23. Django-20220910T174146Z-001
10-09-2022  23:12           635,343 23. Django-20220910T174146Z-001.zip
24-09-2023  23:54            10,895 24_09_practice.sql
13-10-2023  13:47           641,619 25_09_power_bi_practice.pbix
26-09-2023  00:19             1,059 25_09_practice.sql
25-12-2022  23:08           402,470 25resume.pdf
07-10-2022  21:35         2,513,681 25th Sept Industry ready 1-DS Project F

10-06-2023  13:53           428,601 Feb'23 (1).pdf
08-06-2023  09:39           428,601 Feb'23.pdf
16-09-2022  19:48        14,064,278 FifteenThousandUsefulPhrases_10777354.pdf
14-10-2022  14:06    <DIR>          fig_code
21-02-2023  13:56            22,016 file_example_XLS_10.xls
20-11-2022  08:12           189,963 Final Solution.xlsx
19-03-2023  13:15             1,709 final_data.csv
27-02-2023  13:56             8,949 final_file.xlsx
19-04-2023  13:26           414,671 Final_updated_resume19.pdf
14-10-2022  10:50             1,417 finalised_kmeans_model.sav
13-01-2023  22:01             1,613 finalized_model.pickle
14-10-2022  23:45             3,856 finalized_model1456.pickle
23-01-2023  15:22           401,602 finalresume2301.pdf
27-01-2023  11:45           394,597 finalteleresume.pdf
07-06-2023  11:19           392,434 Financial Analytics.pdf
09-10-2022  22:15         3,663,063 firstfigure.html
06-05-2023  17:13    <DIR>          Flask
05-06-2023  11:28    <DIR>          Flask (1)

In [3]:
import pandas as pd

C:\Users\skme2\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [4]:
df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')

In [5]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [427]:
type(df)

pandas.core.frame.DataFrame

In [428]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [429]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [430]:
df.sample()

sepal_length  sepal_width  petal_length  petal_width species
32           5.2          4.1           1.5          0.1  setosa

In [431]:
df.shape

(150, 5)

In [432]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [433]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [434]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [435]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [436]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [440]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [441]:
df.describe('all')

TypeError: '<=' not supported between instances of 'int' and 'numpy.str_'

In [442]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [443]:
df.sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [444]:
df.sepal_width

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [445]:
df['petal_length']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [446]:
df['petal_width']

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ... 
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64

In [448]:
df.species.nunique()

3

In [449]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [454]:
pd.read_csv('IRIS20.csv')

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [456]:
df = pd.read_csv('iris12.csv')

In [461]:
df[df.species == 'setosa'].shape

(50, 5)

In [466]:
df.species.value_counts()['versicolor']

50

In [468]:
df.sepal_length.min()

4.3

In [469]:
df.sepal_width.max()

4.4

In [470]:
df.petal_length.mean()

3.758666666666666

In [471]:
df.petal_width.sum()

179.8

In [472]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [474]:
df.sort_values(by="sepal_length", ascending=False)

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [480]:
df.sort_values(by=['sepal_length', 'sepal_width'], ascending=[False, True], inplace=True)

In [481]:
df

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
8             4.4          2.9           1.4          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [484]:
df.sort_index(inplace=True)

In [485]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [489]:
df.sepal_length.apply(lambda x:x*2)

0      10.2
1       9.8
2       9.4
3       9.2
4      10.0
       ... 
145    13.4
146    12.6
147    13.0
148    12.4
149    11.8
Name: sepal_length, Length: 150, dtype: float64

In [490]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [491]:
df.species.apply(len)

0      6
1      6
2      6
3      6
4      6
      ..
145    9
146    9
147    9
148    9
149    9
Name: species, Length: 150, dtype: int64

In [492]:
df.apply(lambda x:x+x)

sepal_length  sepal_width  petal_length  petal_width             species
0            10.2          7.0           2.8          0.4        setosasetosa
1             9.8          6.0           2.8          0.4        setosasetosa
2             9.4          6.4           2.6          0.4        setosasetosa
3             9.2          6.2           3.0          0.4        setosasetosa
4            10.0          7.2           2.8          0.4        setosasetosa
..            ...          ...           ...          ...                 ...
145          13.4          6.0          10.4          4.6  virginicavirginica
146          12.6          5.0          10.0          3.8  virginicavirginica
147          13.0          6.0          10.4          4.0  virginicavirginica
148          12.4          6.8          10.8          4.6  virginicavirginica
149          11.8          6.0          10.2          3.6  virginicavirginica

[150 rows x 5 columns]

In [493]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [494]:
df.aggregate('min')

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [500]:
df[df.species=='setosa']['sepal_length'].min()

4.9

In [501]:
df[df.species=='setosa']['sepal_width'].min()

2.3

In [502]:
df[df.species=='setosa']['petal_length'].min()

1.0

In [503]:
df[df.species=='setosa']['petal_width'].min()

0.1

In [509]:
df.agg(['min', 'max','mean','std','median'])

<ipython-input-509-ab996a4d760b>:1: FutureWarning: ['species'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.agg(['min', 'max','mean','std','median'])


sepal_length  sepal_width  petal_length  petal_width    species
min         4.300000     2.000000      1.000000     0.100000     setosa
max         7.900000     4.400000      6.900000     2.500000  virginica
mean        5.843333     3.054000      3.758667     1.198667        NaN
std         0.828066     0.433594      1.764420     0.763161        NaN
median      5.800000     3.000000      4.350000     1.300000        NaN

In [510]:
df.species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [512]:
group_object = df.groupby(by='species')

In [513]:
group_object

In [514]:
group_object.min()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [515]:
group_object.max()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [516]:
group_object.median()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0

In [519]:
group_object.aggregate(['min', 'max', 'median', 'std']).T

species                setosa  versicolor  virginica
sepal_length min     4.300000    4.900000   4.900000
             max     5.800000    7.000000   7.900000
             median  5.000000    5.900000   6.500000
             std     0.352490    0.516171   0.635880
sepal_width  min     2.300000    2.000000   2.200000
             max     4.400000    3.400000   3.800000
             median  3.400000    2.800000   3.000000
             std     0.381024    0.313798   0.322497
petal_length min     1.000000    3.000000   4.500000
             max     1.900000    5.100000   6.900000
             median  1.500000    4.350000   5.550000
             std     0.173511    0.469911   0.551895
petal_width  min     0.100000    1.000000   1.400000
             max     0.600000    1.800000   2.500000
             median  0.200000    1.300000   2.000000
             std     0.107210    0.197753   0.274650

In [520]:
group_object.count()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [521]:
df.corr()

<ipython-input-521-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [522]:
group_object.sum()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             250.3        170.9          73.2         12.2
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [524]:
group_object.describe().T

species                setosa  versicolor  virginica
sepal_length count  50.000000   50.000000  50.000000
             mean    5.006000    5.936000   6.588000
             std     0.352490    0.516171   0.635880
             min     4.300000    4.900000   4.900000
             25%     4.800000    5.600000   6.225000
             50%     5.000000    5.900000   6.500000
             75%     5.200000    6.300000   6.900000
             max     5.800000    7.000000   7.900000
sepal_width  count  50.000000   50.000000  50.000000
             mean    3.418000    2.770000   2.974000
             std     0.381024    0.313798   0.322497
             min     2.300000    2.000000   2.200000
             25%     3.125000    2.525000   2.800000
             50%     3.400000    2.800000   3.000000
             75%     3.675000    3.000000   3.175000
             max     4.400000    3.400000   3.800000
petal_length count  50.000000   50.000000  50.000000
             mean    1.464000    4.260000   5.552000
             std     0.173511    0.469911   0.551895
             min     1.000000    3.000000   4.500000
             25%     1.400000    4.000000   5.100000
             50%     1.500000    4.350000   5.550000
             75%     1.575000    4.600000   5.875000
             max     1.900000    5.100000   6.900000
petal_width  count  50.000000   50.000000  50.000000
             mean    0.244000    1.326000   2.026000
             std     0.107210    0.197753   0.274650
             min     0.100000    1.000000   1.400000
             25%     0.200000    1.200000   1.800000
             50%     0.200000    1.300000   2.000000
             75%     0.300000    1.500000   2.300000
             max     0.600000    1.800000   2.500000

In [526]:
import warnings
warnings.filterwarnings('ignore')

df.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [528]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [532]:
nan_indx = np.random.randint(0,150,20)

In [536]:
df['sepal_width'][nan_indx] = np.nan

In [537]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          NaN           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [539]:
idx_nan = np.random.randint(0,150,15)

In [543]:
df.petal_width[idx_nan] = np.nan

In [544]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          NaN           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

[150 rows x 5 columns]

In [546]:
df.isna().sum()

sepal_length     0
sepal_width     20
petal_length     0
petal_width     13
species          0
dtype: int64

In [547]:
df.shape

(150, 5)

In [548]:
df.dropna()

sepal_length  sepal_width  petal_length  petal_width    species
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
..            ...          ...           ...          ...        ...
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica

[119 rows x 5 columns]

In [549]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          NaN           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

[150 rows x 5 columns]

In [552]:
df.fillna('sanjay')

sepal_length sepal_width  petal_length petal_width    species
0             5.1      sanjay           1.4         0.2     setosa
1             4.9         3.0           1.4         0.2     setosa
2             4.7         3.2           1.3         0.2     setosa
3             4.6         3.1           1.5         0.2     setosa
4             5.0         3.6           1.4         0.2     setosa
..            ...         ...           ...         ...        ...
145           6.7         3.0           5.2         2.3  virginica
146           6.3         2.5           5.0         1.9  virginica
147           6.5         3.0           5.2         2.0  virginica
148           6.2         3.4           5.4         2.3  virginica
149           5.9         3.0           5.1      sanjay  virginica

[150 rows x 5 columns]

In [560]:
np.round(df.sepal_width.mean(),1)

3.0

In [561]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          NaN           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

[150 rows x 5 columns]

In [564]:
df.sepal_width.fillna(value=np.round(df.sepal_width.mean(),1), inplace=True)

In [565]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.0           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

[150 rows x 5 columns]

In [567]:
df.petal_width[:50]

0     0.2
1     0.2
2     0.2
3     0.2
4     0.2
5     0.4
6     0.3
7     0.2
8     0.2
9     0.1
10    0.2
11    0.2
12    0.1
13    0.1
14    0.2
15    0.4
16    0.4
17    0.3
18    0.3
19    0.3
20    0.2
21    0.4
22    0.2
23    0.5
24    0.2
25    0.2
26    0.4
27    0.2
28    0.2
29    0.2
30    0.2
31    0.4
32    0.1
33    0.2
34    0.1
35    0.2
36    0.2
37    0.1
38    0.2
39    0.2
40    0.3
41    0.3
42    0.2
43    0.6
44    NaN
45    0.3
46    0.2
47    0.2
48    0.2
49    0.2
Name: petal_width, dtype: float64

In [571]:
round(df.petal_width.mean(),1)

1.2

In [575]:
df.petal_width.fillna(value=round(df.petal_width.mean(),1), inplace=True)

In [576]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.0           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.2  virginica

[150 rows x 5 columns]

In [577]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.0           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.2  virginica

[150 rows x 5 columns]

In [579]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [1]:
# concat/ Merge DataFrames

In [6]:
import numpy as np

In [7]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [10]:
arr1 = np.random.randint(0,7,size = (10,4))

In [12]:
df2 = pd.DataFrame(arr1)

In [15]:
df2['species'] = "new-species"

In [16]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [17]:
df2

0  1  2  3      species
0  0  2  1  0  new-species
1  1  2  5  5  new-species
2  2  0  2  1  new-species
3  4  6  2  5  new-species
4  3  6  5  0  new-species
5  6  2  1  3  new-species
6  6  5  4  6  new-species
7  1  6  0  1  new-species
8  0  0  3  2  new-species
9  0  2  3  1  new-species

In [18]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [19]:
df2.columns = df.columns

In [20]:
df2

sepal_length  sepal_width  petal_length  petal_width      species
0             0            2             1            0  new-species
1             1            2             5            5  new-species
2             2            0             2            1  new-species
3             4            6             2            5  new-species
4             3            6             5            0  new-species
5             6            2             1            3  new-species
6             6            5             4            6  new-species
7             1            6             0            1  new-species
8             0            0             3            2  new-species
9             0            2             3            1  new-species

In [43]:
df5 = pd.concat([df,df2])

In [23]:
pd.concat([df,df2], axis=1)

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     sepal_length  sepal_width  petal_length  petal_width      species  
0             0.0          2.0           1.0          0.0  new-species  
1             1.0          2.0           5.0          5.0  new-species  
2             2.0          0.0           2.0          1.0  new-species  
3             4.0          6.0           2.0          5.0  new-species  
4             3.0          6.0           5.0          0.0  new-species  
..            ...          ...           ...          ...          ...  
145           NaN          NaN           NaN          NaN          NaN  
146           NaN          NaN           NaN          NaN          NaN  
147           NaN          NaN           NaN          NaN          NaN  
148           NaN          NaN           NaN          NaN          NaN  
149           NaN          NaN           NaN          NaN          NaN  

[150 rows x 10 columns]

In [24]:
# Merging DataFrame

In [26]:
df3  = pd.DataFrame({
    'S_Name':['Mohit', 'Jatin', 'Prateek','Mohit'],"CGPA":[2,4,5,3]})

In [27]:
df3

S_Name  CGPA
0    Mohit     2
1    Jatin     4
2  Prateek     5
3    Mohit     3

In [28]:
t = {
    "T_Name":['Mohit', 'Jatin', 'Prateek', 'Mohit'],
    'CGPA':[3,6,8,9]
}

In [29]:
t

{'T_Name': ['Mohit', 'Jatin', 'Prateek', 'Mohit'], 'CGPA': [3, 6, 8, 9]}

In [31]:
df4 = pd.DataFrame(t)

In [32]:
df4

T_Name  CGPA
0    Mohit     3
1    Jatin     6
2  Prateek     8
3    Mohit     9

In [33]:
df3.merge(df4)

S_Name  CGPA T_Name
0  Mohit     3  Mohit

In [34]:
df3.merge(df4,how='inner',on='CGPA' )

S_Name  CGPA T_Name
0  Mohit     3  Mohit

In [35]:
df3.merge(df4, how='left', on='CGPA')

S_Name  CGPA T_Name
0    Mohit     2    NaN
1    Jatin     4    NaN
2  Prateek     5    NaN
3    Mohit     3  Mohit

In [36]:
df3.merge(df4, how='right', on='CGPA')

S_Name  CGPA   T_Name
0  Mohit     3    Mohit
1    NaN     6    Jatin
2    NaN     8  Prateek
3    NaN     9    Mohit

In [37]:
df3.merge(df4, how='outer', on='CGPA')

S_Name  CGPA   T_Name
0    Mohit     2      NaN
1    Jatin     4      NaN
2  Prateek     5      NaN
3    Mohit     3    Mohit
4      NaN     6    Jatin
5      NaN     8  Prateek
6      NaN     9    Mohit

In [39]:
df3.merge(df4, how='cross')

S_Name  CGPA_x   T_Name  CGPA_y
0     Mohit       2    Mohit       3
1     Mohit       2    Jatin       6
2     Mohit       2  Prateek       8
3     Mohit       2    Mohit       9
4     Jatin       4    Mohit       3
5     Jatin       4    Jatin       6
6     Jatin       4  Prateek       8
7     Jatin       4    Mohit       9
8   Prateek       5    Mohit       3
9   Prateek       5    Jatin       6
10  Prateek       5  Prateek       8
11  Prateek       5    Mohit       9
12    Mohit       3    Mohit       3
13    Mohit       3    Jatin       6
14    Mohit       3  Prateek       8
15    Mohit       3    Mohit       9

In [40]:
# output Files

In [41]:
ls

 Volume in drive C is OS
 Volume Serial Number is 0CC1-C20F

 Directory of C:\Users\skme2\Downloads

13-02-2024  08:20    <DIR>          .
12-02-2024  18:58    <DIR>          ..
12-02-2024  23:02    <DIR>          .ipynb_checkpoints
21-12-2023  11:58    <DIR>          __pycache__
06-11-2023  11:20             2,633 01_11_sql_practice.sql
02-11-2022  15:49           410,816 0211resume.pdf
03-09-2023  14:20            54,756 03_09_1_pm_Functions.ipynb
13-10-2023  15:25    <DIR>          03_10_4pm
13-10-2023  15:24        98,232,624 03_10_4pm.zip
20-03-2023  16:51           118,844 04_06.ipynb
13-10-2023  15:24    <DIR>          04_10_4pm
13-10-2023  15:23        85,733,531 04_10_4pm.zip
04-12-2023  16:36               185 04_12_03_05_pm.sql
05-12-2023  11:43            78,452 04_12_python_class_2.ipynb
05-08-2023  17:33       144,122,096 05_08_1PM.zip
05-08-2023  17:32            28,266 05_08_firoj_tapan.ipynb
05-12-2023  17:47             1,293 05_12_03_05_pm.sql
06-12-2023  12:35      

In [42]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [44]:
df5

sepal_length  sepal_width  petal_length  petal_width      species
0            5.1          3.5           1.4          0.2       setosa
1            4.9          3.0           1.4          0.2       setosa
2            4.7          3.2           1.3          0.2       setosa
3            4.6          3.1           1.5          0.2       setosa
4            5.0          3.6           1.4          0.2       setosa
..           ...          ...           ...          ...          ...
5            6.0          2.0           1.0          3.0  new-species
6            6.0          5.0           4.0          6.0  new-species
7            1.0          6.0           0.0          1.0  new-species
8            0.0          0.0           3.0          2.0  new-species
9            0.0          2.0           3.0          1.0  new-species

[160 rows x 5 columns]

In [47]:
df.size

750

In [46]:
df5.size

800

In [49]:
df5.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [50]:
df5

sepal_length  sepal_width  petal_length  petal_width      species
0            5.1          3.5           1.4          0.2       setosa
1            4.9          3.0           1.4          0.2       setosa
2            4.7          3.2           1.3          0.2       setosa
3            4.6          3.1           1.5          0.2       setosa
4            5.0          3.6           1.4          0.2       setosa
..           ...          ...           ...          ...          ...
5            6.0          2.0           1.0          3.0  new-species
6            6.0          5.0           4.0          6.0  new-species
7            1.0          6.0           0.0          1.0  new-species
8            0.0          0.0           3.0          2.0  new-species
9            0.0          2.0           3.0          1.0  new-species

[160 rows x 5 columns]

In [53]:
df5.to_csv('revision_n_p.csv', index=False)

In [55]:
df5.to_excel('excelfile.xlsx', index=False, sheet_name = "sales1220")

<ipython-input-55-3f8002ffba45>:1: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  df5.to_excel('excelfile.xlsx', index=False, sheet_name = "sales1220")
